import tkinter as tk
from tkinter import ttk

#define the outer window
window = tk.Tk()
window.geometry('800x600')
window.title("Thumbnail Recommender & Scene Detector")

#define the notebook and both frames
notebook = ttk.Notebook(window)
notebook.pack(fill="both", expand=True)
frame1 = tk.Frame(notebook)
frame2 = tk.Frame(notebook)
frame1.pack(fill="both", expand=True)
frame2.pack(fill="both", expand=True)
notebook.add(frame1, text="Thumbnail Recommender")
notebook.add(frame2, text="Scene Detector")

#thumbnail recommender frame
LeftFrame1 = tk.Frame(frame1, width=200)
LeftFrame1.pack(side=tk.LEFT, fill=tk.Y, expand=False)
RightFrame1 = tk.Frame(frame1, background="blue")
RightFrame1.pack(side=tk.LEFT, fill="both", expand=True)

controlFrame1 = tk.Frame(LeftFrame1, width=200)
controlFrame1.pack(side=tk.TOP, expand=False)
sourceSelectLabel1 = tk.Label(controlFrame1, text="Video Source:", width=15)
sourceSelectLabel1.grid(padx=2, pady=2, row=0, column=0)
sourceSelect1 = ttk.Combobox(controlFrame1, state="readonly", values=("Clip 1", "Clip 2", "Clip 3", "Use local file"), width=15)
sourceSelect1.current(0)
sourceSelect1.grid(padx=2, pady=2, row=0, column=1)
localPathLabel1 = tk.Label(controlFrame1, text="", width=15, fg="blue", anchor="w")
localPathLabel1.grid(padx=2, pady=2, row=1, column=0)
localPathButton1 = tk.Button(controlFrame1, text="Browse local files", width=15)
localPathButton1.grid(padx=2, pady=2, row=1, column=1)
FPSLabel1 = tk.Label(controlFrame1, text="Analysis FPS:", width=15)
FPSLabel1.grid(padx=2, pady=2, row=2, column=0)
FPSSelect1 = ttk.Combobox(controlFrame1, state="readonly", values=(0.5, 1, 2, 3, 5), width=15)
FPSSelect1.current(2)
FPSSelect1.grid(padx=2, pady=2, row=2, column=1)
ResLabel1 = tk.Label(controlFrame1, text="Analysis Resolution:", width=15)
ResLabel1.grid(padx=2, pady=2, row=3, column=0)
ResSelect1 = ttk.Combobox(controlFrame1, state="readonly", values=("50x50", "100x100", "200x200", "500x500"), width=15)
ResSelect1.current(1)
ResSelect1.grid(padx=2, pady=2, row=3, column=1)
ThumbnailsLabel1 = tk.Label(controlFrame1, text="Thumbnails:", width=15)
ThumbnailsLabel1.grid(padx=2, pady=2, row=4, column=0)
ThumbnailSelect1 = ttk.Combobox(controlFrame1, state="readonly", values=(1, 2, 3, 4, 5, 6, 7, 8, 9, 10), width=15)
ThumbnailSelect1.current(4)
ThumbnailSelect1.grid(padx=2, pady=2, row=4, column=1)
IterationsLabel1 = tk.Label(controlFrame1, text="Iterations:", width=15)
IterationsLabel1.grid(padx=2, pady=2, row=5, column=0)
IterationsSelect1 = ttk.Combobox(controlFrame1, state="readonly", values=(5, 10, 15, 20, 50, 100), width=15)
IterationsSelect1.current(1)
IterationsSelect1.grid(padx=2, pady=2, row=5, column=1)
StartButton1 = tk.Button(LeftFrame1, text="Generate Thumbnails", width=31)
StartButton1.pack(padx=2, pady=2, expand=False)
ProgressBar1 = ttk.Progressbar(LeftFrame1, length=225, mode="determinate")
ProgressBar1.pack(padx=2, pady=2, expand=False)

#thumbnail recommender frame
controlFrame2 = tk.Frame(frame2, width=200)
controlFrame2.pack(side=tk.LEFT, fill=tk.Y, expand=False)
outputFrame2 = tk.Frame(frame2, background="red")
outputFrame2.pack(side=tk.LEFT, fill="both", expand=True)
sourceSelectLabel2 = tk.Label(controlFrame2, text="Video Source:", width=15)
sourceSelectLabel2.grid(padx=2, pady=2, row=0, column=0)
sourceSelect2 = ttk.Combobox(controlFrame2, state="readonly", values=("Clip 1", "Clip 2", "Clip 3", "Use local file"), width=15)
sourceSelect2.current(0)
sourceSelect2.grid(padx=2, pady=2, row=0, column=1)
localPathLabel2 = tk.Label(controlFrame2, text="", width=15, fg="blue", anchor="w")
localPathLabel2.grid(padx=2, pady=2, row=1, column=0)
localPathButton2 = tk.Button(controlFrame2, text="Browse local files", width=15)
localPathButton2.grid(padx=2, pady=2, row=1, column=1)
FPSLabel2 = tk.Label(controlFrame2, text="Analysis FPS:", width=15)
FPSLabel2.grid(padx=2, pady=2, row=2, column=0)
FPSSelect2 = ttk.Combobox(controlFrame2, state="readonly", values=(0.5, 1, 2, 3, 5), width=15)
FPSSelect2.current(2)
FPSSelect2.grid(padx=2, pady=2, row=2, column=1)
ResLabel2 = tk.Label(controlFrame2, text="Analysis Resolution:", width=15)
ResLabel2.grid(padx=2, pady=2, row=3, column=0)
ResSelect2 = ttk.Combobox(controlFrame2, state="readonly", values=("50x50", "100x100", "200x200", "500x500"), width=15)
ResSelect2.current(1)
ResSelect2.grid(padx=2, pady=2, row=3, column=1)
ThumbnailsLabel2 = tk.Label(controlFrame2, text="Thumbnails:", width=15)
ThumbnailsLabel2.grid(padx=2, pady=2, row=4, column=0)
ThumbnailSelect2 = ttk.Combobox(controlFrame2, state="readonly", values=(1, 2, 3, 4, 5, 6, 7, 8, 9, 10), width=15)
ThumbnailSelect2.current(4)
ThumbnailSelect2.grid(padx=2, pady=2, row=4, column=1)
IterationsLabel2 = tk.Label(controlFrame2, text="Iterations:", width=15)
IterationsLabel2.grid(padx=2, pady=2, row=5, column=0)
IterationsSelect2 = ttk.Combobox(controlFrame2, state="readonly", values=(5, 10, 15, 20, 50, 100), width=15)
IterationsSelect2.current(1)
IterationsSelect2.grid(padx=2, pady=2, row=5, column=1)

window.mainloop()